FROM mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app
EXPOSE 80
COPY Shared/SharedLibrary/*.csproj Shared/SharedLibrary/
COPY Services/Reservation/Reservation.API/*.csproj Services/Reservation/Reservation.API/
RUN dotnet restore Services/Reservation/Reservation.API/*.csproj
COPY . .
RUN dotnet publish Services/Reservation/Reservation.API/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "Reservation.API.dll"]