version: "3.8"
services:
    locationdb:
        container_name: locationdb
        restart: always
        ports:
        - "6789:5432"
        environment:
            POSTGRES_USER : postgres
            POSTGRES_PASSWORD : postgres
            POSTGRES_DB : eniyisiNeredeDB
        volumes:
            - locationdb_volume:/var/lib/postgresql/data
    
    identitydb:
        container_name: identitydb
        restart: always
        ports:
        - "1234:1433"
        environment:
            MSSQL_SA_PASSWORD: "Password1234"
            ACCEPT_EULA: "Y"
        volumes:
            - identitydb_volume:/var/opt/mssql

    productdb:
        container_name: productdb
        restart: always
        ports:
        - "5678:1433"
        environment:
            MSSQL_SA_PASSWORD: "Password1234"
            ACCEPT_EULA: "Y"
        volumes:
            - productdb_volume:/var/opt/mssql

    placedb:
        container_name: placedb
        restart: always
        ports:
        - "27017:27017"
        volumes:
            - placedb_volume:/data/db
    
    location.api:
        container_name: location.api
        ports:
        - "5011:443"
        environment:
           - IdentityServerUrl=http://identityserver.api
           - ASPNETCORE_ENVIRONMENT=Development
           - "ConnectionStrings:DefaultConnection=Server=localhost; Port=6789;Database=eniyisiNeredeDB;User Id=postgres;Password=postgres;"
        depends_on:
           - locationdb

    identityserver.api:
        container_name: identityserver.api
        restart : on-failure
        ports:
        - "5050:443"
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - "ConnectionStrings:DefaultConnection=Server=localhost; Port=1234;Database=eniyisiNeredeIdentityDB;User Id=sa;Password=Password1234;" 
        depends_on:
           - identitydb

    place.api:
        container_name: place.api
        ports:
        - "5012:443"
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - DatabaseSettings:ConnectionString=mongodb://localhost:27017
        depends_on:
           - placedb    
    
    product.api:
        container_name: product.api
        restart : on-failure
        ports:
        - "5012:443"
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - "ConnectionStrings:DefaultConnection=Server=localhost;Port=5678;Database=eniyisiNeredeProductDB;User Id=sa;Password=Password1234;" 
        depends_on:
           - productdb